# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version('>= 2.0')
unless Vagrant.has_plugin?('vagrant-vyos')
  system('vagrant plugin install vagrant-vyos') || exit!
end

Vagrant.configure(2) do |config|

  ##### DEFINE VM for leftrouter #####
  config.vm.define "leftrouter" do |device|
    
    device.vm.hostname = "leftrouter" 
    device.vm.box = "higebu/vyos"
    device.vm.box_version = "1.1.7"

    device.vm.provider "virtualbox" do |v|
      v.name = "leftrouter"
      v.memory = 768
    end
    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
    device.vm.synced_folder ".", "/vagrant", disabled: true

    # NETWORK INTERFACES      
      # link for eth --> oob-mgmt-switch:
      device.vm.network "private_network", ip: "192.168.0.100"

      # link for eth --> right_router
      device.vm.network "private_network", virtualbox__intnet: "net5", auto_config: false

  end

  ##### DEFINE VM for right_router #####
  config.vm.define "rightrouter" do |device|
    
    device.vm.hostname = "rightrouter" 
    device.vm.box = "higebu/vyos"
    device.vm.box_version = "1.1.7"

    device.vm.provider "virtualbox" do |v|
      v.name = "rightrouter"
      v.memory = 768
    end
    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
    device.vm.synced_folder ".", "/vagrant", disabled: true

    # NETWORK INTERFACES      
      # link for eth --> oob-mgmt-switch:
      device.vm.network "private_network", ip: "192.168.0.101"

      # link for eth --> right_router
      device.vm.network "private_network", virtualbox__intnet: "net5", auto_config: false

  end

  ##### DEFINE VM for MGMT #####
  config.vm.define "mgmt" do |device|
    device.vm.hostname = "mgmt" 
    
    device.vm.box = "ubuntu/xenial64"
    device.vm.provider "virtualbox" do |v|
      v.name = "mgmt"
      v.linked_clone = true
      v.memory = 512
    end
    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
    device.vm.synced_folder "helper_scripts", "/vagrant/helper_scripts"
    device.vm.synced_folder "sot", "/vagrant/sot"

    device.vm.network "private_network", ip: "192.168.0.200"

    # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
    device.vm.provision :shell , inline: "(sudo grep -q 'mesg n' /root/.profile 2>/dev/null && sudo sed -i '/mesg n/d' /root/.profile  2>/dev/null) || true;", privileged: false

    # Shorten Boot Process - Applies to Ubuntu Only - remove \"Wait for Network\"
    device.vm.provision :shell , inline: "sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf 2>/dev/null || true"

    # Copy hosts file to /etc/hosts
    device.vm.provision :shell , inline: "sudo cp /vagrant/helper_scripts/hosts /etc/hosts"

    # Copy secret key
    device.vm.provision :shell , inline: "sudo cp /vagrant/helper_scripts/id_rsa /home/vagrant/.ssh/id_rsa"

  end

end
