---

- name: PLAY1
  hosts: routers
  connection: local
  gather_facts: false
  
  tasks:
    - name: "do something for play 1"
      vyos_command:
        commands:
          - show version
          - show hardware cpu
        wait_for:
          - "result[0] contains 'VyOS 1.1.7'"

- name: PLAY2
  hosts: switches
  
  tasks:
    - name: "do something for play2"
      fetch: dest=save/{{ansible_hostname}}/interfaces src=/etc/network/interfaces flat=yes

    - name: "do something else for play2"
      nclu:
        commands:
          - show configuration commands

          